### ISSUE TITLE
Running Examples and BOM CI on Hetzner

### ISSUE THREAD

**Issue by gytis** [snowdrop/project#72]
Today I tried the OpenShift GitHub action and it is very easy to use. If we have enough capacity on our Hetzner machine we could consider running our CI tests of the examples and BOM like this instead of the CircleCI. It would make the configuration easier and running time shorter since the OpenShift instance would be always available.

Here's the config that I used for the secured example:
```
name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2        
    - name: Create OpenShift project
      uses: redhat-developer/openshift-actions@v2.0
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: |
          oc new-project gh-action
          oc apply -f service.sso.yaml
    - name: Run tests
      run: ./mvnw clean verify -Popenshift,openshift-it -DSSO_AUTH_SERVER_URL=$(oc get route secure-sso -o jsonpath='https://{.spec.host}/auth')
    - name: Delete OpenShift project
      uses: redhat-developer/openshift-actions@v2.0
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: oc delete project gh-action
```

Of course we should make it more sophisticated with unique project names, storing failed logs etc. But setup is still much simpler in comparison to having to bootup an OpenShift instance in CircleCI for every run. Any thoughts @cmoulliard @geoand @jacobdotcosta @metacosm @iocanel @aureamunoz?
